#pragma once
#include "includes.hpp"
#include "resource.h"
#include "crypto_key.hpp"   // auto-generated by encrypt_bins.ps1 (Pre-Build)
#include "log.hpp"
#include "VMProtectSDK.h"   // VMProtect 3.x SDK

#include <bcrypt.h>
// bcrypt.lib is NOT linked statically – all symbols are resolved at runtime
// via LoadLibraryW / GetProcAddress so they never appear in the binary IAT.

//=============================================================================
//  embedded.hpp  –  AES-256-CBC decryption of RCDATA resources to %TEMP%
//
//  encrypt_bins.ps1 (Pre-Build event) does:
//    1. Builds MidnightSoftwareDriver.sys + DMA-SDK.exe via MSBuild
//    2. Generates a fresh random AES-256 key each build
//    3. Splits the key into 3 XOR-obfuscated parts → src/crypto_key.hpp
//    4. AES-256-CBC encrypts kvc.sys / MidnightSoftwareDriver.sys / DMA-SDK.exe → *.bin
//    5. driver_loader.rc embeds the .bin files as RCDATA (101/102/103)
//
//  At runtime Init() reconstructs the key, decrypts, and drops to %TEMP%.
//  Cleanup() zero-wipes kvc.sys and DMA-SDK.exe from %TEMP%.
//=============================================================================

namespace embedded {

inline std::wstring g_kvc_path;
inline std::wstring g_driver_path;
inline std::wstring g_payload_path;

// Generate a unique random 10-char hex string for temp file names.
// A static counter ensures each call returns a distinct value even when
// called multiple times within the same millisecond.
inline std::wstring rand_stem() noexcept
{
    static unsigned long long s_ctr = 0;
    FILETIME ft{}; ::GetSystemTimeAsFileTime(&ft);
    ULARGE_INTEGER ui; ui.LowPart = ft.dwLowDateTime; ui.HighPart = ft.dwHighDateTime;
    DWORD pid  = ::GetCurrentProcessId();
    DWORD tick = ::GetTickCount();
    unsigned long long seed = ui.QuadPart
                            ^ ((unsigned long long)pid  << 17)
                            ^ ((unsigned long long)tick << 5)
                            ^ (++s_ctr * 6364136223846793005ULL);
    // xorshift64
    seed ^= seed << 13; seed ^= seed >> 7; seed ^= seed << 17;
    wchar_t buf[11];
    const wchar_t hex[] = L"0123456789abcdef";
    for (int i = 0; i < 10; ++i) { buf[i] = hex[seed & 0xF]; seed >>= 4; }
    buf[10] = L'\0';
    return buf;
}

namespace detail {

// Runtime-format helper: std::format requires a compile-time literal, but
// WOBFS() produces a runtime-decrypted wstring.  Use wfmt() everywhere so
// the obfuscated format string is fully decrypted only inside the call.
template<class... Args>
[[nodiscard]] inline std::wstring wfmt( std::wstring fmt_str, Args... args )
{
    return std::vformat( std::wstring_view( fmt_str ),
        std::make_wformat_args( args... ) );
}

// ──────────────────── lazy BCrypt API (no IAT entries at all) ─────────────────
// None of the BCrypt* names, and not even "bcrypt.dll", appear as plaintext
// in the binary: the DLL name is WOBF-encrypted and each export name is
// OBF-encrypted. Resolution happens once on first call to bcrypt_loader::get().
namespace bcrypt_loader {

using fn_OpenAlg   = NTSTATUS(WINAPI*)(BCRYPT_ALG_HANDLE*, LPCWSTR, LPCWSTR, ULONG);
using fn_CloseAlg  = NTSTATUS(WINAPI*)(BCRYPT_ALG_HANDLE, ULONG);
using fn_SetProp   = NTSTATUS(WINAPI*)(BCRYPT_HANDLE, LPCWSTR, PUCHAR, ULONG, ULONG);
using fn_GetProp   = NTSTATUS(WINAPI*)(BCRYPT_HANDLE, LPCWSTR, PUCHAR, ULONG, ULONG*, ULONG);
using fn_GenSymKey = NTSTATUS(WINAPI*)(BCRYPT_ALG_HANDLE, BCRYPT_KEY_HANDLE*, PUCHAR, ULONG, PUCHAR, ULONG, ULONG);
using fn_DestrKey  = NTSTATUS(WINAPI*)(BCRYPT_KEY_HANDLE);
using fn_Decrypt   = NTSTATUS(WINAPI*)(BCRYPT_KEY_HANDLE, PUCHAR, ULONG, VOID*, PUCHAR, ULONG, PUCHAR, ULONG, ULONG*, ULONG);

struct api_t {
    fn_OpenAlg   OpenAlgorithmProvider  = nullptr;
    fn_CloseAlg  CloseAlgorithmProvider = nullptr;
    fn_SetProp   SetProperty            = nullptr;
    fn_GetProp   GetProperty            = nullptr;
    fn_GenSymKey GenerateSymmetricKey   = nullptr;
    fn_DestrKey  DestroyKey             = nullptr;
    fn_Decrypt   Decrypt                = nullptr;
    bool         loaded                 = false;
};

[[nodiscard]] inline api_t& get() noexcept
{
    static api_t s;
    if ( s.loaded ) return s;

    // DLL name is wide-encrypted; never a plaintext L"bcrypt.dll" in .rdata
    HMODULE hDll = ::LoadLibraryW( WOBF( L"bcrypt.dll" ) );
    if ( !hDll ) return s;

    auto R = [&]( const char* n ) -> FARPROC { return ::GetProcAddress( hDll, n ); };

    // Every export name is narrow-encrypted; none survive as plaintext in .rdata
    s.OpenAlgorithmProvider  = reinterpret_cast<fn_OpenAlg>  ( R( OBF( "BCryptOpenAlgorithmProvider"  ) ) );
    s.CloseAlgorithmProvider = reinterpret_cast<fn_CloseAlg> ( R( OBF( "BCryptCloseAlgorithmProvider" ) ) );
    s.SetProperty            = reinterpret_cast<fn_SetProp>  ( R( OBF( "BCryptSetProperty"            ) ) );
    s.GetProperty            = reinterpret_cast<fn_GetProp>  ( R( OBF( "BCryptGetProperty"            ) ) );
    s.GenerateSymmetricKey   = reinterpret_cast<fn_GenSymKey>( R( OBF( "BCryptGenerateSymmetricKey"   ) ) );
    s.DestroyKey             = reinterpret_cast<fn_DestrKey> ( R( OBF( "BCryptDestroyKey"             ) ) );
    s.Decrypt                = reinterpret_cast<fn_Decrypt>  ( R( OBF( "BCryptDecrypt"                ) ) );
    s.loaded = true;
    return s;
}

} // namespace bcrypt_loader

//─────────────────────────── key reconstruction ───────────────────────────────
// Assembles the true AES-256 key at runtime from the 3 stored XOR parts.
// k[i] = KEY_P1[i] ^ KEY_P2[i] ^ KEY_P3[i]
inline void reconstruct_key( BYTE out[32] ) noexcept
{
    for ( int i = 0; i < 32; ++i )
        out[i] = crypto_key::KEY_P1[i]
               ^ crypto_key::KEY_P2[i]
               ^ crypto_key::KEY_P3[i];
}

//─────────────────────────── AES-256-CBC decrypt ──────────────────────────────
// Decrypts [cipher, cipher+cipher_len) with key32 + iv16.
// Returns decrypted bytes, or empty vector on any failure.
[[nodiscard]]
inline std::vector<BYTE> aes256_cbc_decrypt(
    const BYTE* cipher,     DWORD  cipher_len,
    const BYTE  key32[32],
    const BYTE  iv16[16] ) noexcept
{
    std::vector<BYTE> result;

    auto& bc = bcrypt_loader::get();
    if ( !bc.loaded ) return result;   // DLL load failed

    BCRYPT_ALG_HANDLE hAlg = nullptr;
    NTSTATUS st = bc.OpenAlgorithmProvider(
        &hAlg, BCRYPT_AES_ALGORITHM, nullptr, 0 );
    if ( !BCRYPT_SUCCESS( st ) ) return result;

    // CBC mode
    st = bc.SetProperty(
        hAlg, BCRYPT_CHAINING_MODE,
        reinterpret_cast<PUCHAR>( const_cast<wchar_t*>( BCRYPT_CHAIN_MODE_CBC ) ),
        sizeof( BCRYPT_CHAIN_MODE_CBC ), 0 );
    if ( !BCRYPT_SUCCESS( st ) ) {
        bc.CloseAlgorithmProvider( hAlg, 0 );
        return result;
    }

    // Key object size
    DWORD keyObjSize = 0, cbRes = 0;
    bc.GetProperty( hAlg, BCRYPT_OBJECT_LENGTH,
        reinterpret_cast<PUCHAR>( &keyObjSize ), sizeof(DWORD), &cbRes, 0 );
    std::vector<BYTE> keyObj( keyObjSize );

    BCRYPT_KEY_HANDLE hKey = nullptr;
    st = bc.GenerateSymmetricKey(
        hAlg, &hKey,
        keyObj.data(), keyObjSize,
        const_cast<PUCHAR>( key32 ), 32, 0 );
    if ( !BCRYPT_SUCCESS( st ) ) {
        bc.CloseAlgorithmProvider( hAlg, 0 );
        return result;
    }

    // Helper: single BCryptDecrypt call with a fresh IV copy each time
    auto do_decrypt = [&]( BYTE* out_buf, DWORD& out_sz ) -> NTSTATUS {
        BYTE iv[16];
        ::memcpy( iv, iv16, 16 );
        return bc.Decrypt(
            hKey,
            const_cast<PUCHAR>( cipher ), cipher_len,
            nullptr,
            iv, 16,
            out_buf, out_sz, &out_sz,
            BCRYPT_BLOCK_PADDING );
    };

    // Pass 1: query required output buffer size
    DWORD plain_sz = 0;
    st = do_decrypt( nullptr, plain_sz );
    if ( !BCRYPT_SUCCESS( st ) ) {
        bc.DestroyKey( hKey );
        bc.CloseAlgorithmProvider( hAlg, 0 );
        return result;
    }

    // Pass 2: actual decryption
    result.resize( plain_sz );
    st = do_decrypt( result.data(), plain_sz );
    result.resize( plain_sz );                     // trim PKCS7 padding

    bc.DestroyKey( hKey );
    bc.CloseAlgorithmProvider( hAlg, 0 );

    if ( !BCRYPT_SUCCESS( st ) ) result.clear();
    return result;
}

//─────────────────────────── extract + decrypt ────────────────────────────────
// Loads encrypted RCDATA, decrypts in memory, writes plaintext to %TEMP%.
// Returns the temp file path, or empty string on any failure.
[[nodiscard]]
inline std::wstring extract_and_decrypt(
    int            resource_id,
    const wchar_t* filename,
    const BYTE     key32[32],
    const BYTE     iv16[16] ) noexcept
{
    dlog::write( wfmt( WOBFS(L"[embedded] extracting resource {} -> {}"), resource_id, filename ) );

    HRSRC hRes = ::FindResourceW( nullptr,
        MAKEINTRESOURCEW( resource_id ), RT_RCDATA );
    if ( !hRes ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 FindResourceW({}) failed (GLE {})"),
                            resource_id, ::GetLastError() ) );
        return L"";
    }

    HGLOBAL hGlob = ::LoadResource( nullptr, hRes );
    if ( !hGlob ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 LoadResource({}) failed (GLE {})"),
                            resource_id, ::GetLastError() ) );
        return L"";
    }

    const BYTE* enc  = static_cast<const BYTE*>( ::LockResource( hGlob ) );
    const DWORD elen = ::SizeofResource( nullptr, hRes );
    if ( !enc || elen == 0 ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 LockResource/SizeofResource returned null/0 (id {})"),
                            resource_id ) );
        return L"";
    }
    dlog::write( wfmt( WOBFS(L"[embedded] resource {} size: {} bytes - decrypting..."), resource_id, elen ) );

    // Decrypt – all ciphertext in memory, never touches disk
    auto plain = aes256_cbc_decrypt( enc, elen, key32, iv16 );
    if ( plain.empty() ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 AES-256-CBC decrypt failed for resource {} "
                                 L"(wrong key/IV or corrupt resource)"), resource_id ) );
        return L"";
    }
    dlog::write( wfmt( WOBFS(L"[embedded] decrypted {} bytes OK"), plain.size() ) );

    // Write to %TEMP%
    wchar_t tmpDir[MAX_PATH];
    if ( ::GetTempPathW( MAX_PATH, tmpDir ) == 0 ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 GetTempPathW failed (GLE {})"),
                            ::GetLastError() ) );
        ::SecureZeroMemory( plain.data(), plain.size() );
        return L"";
    }

    // Build the primary path and a PID-unique fallback path.
    // If the primary path is locked (running driver service holds the file
    // open with a share-deny-delete lock), SCM prevents DeleteFileW from
    // removing it even with FILE_FLAG_DELETE_ON_CLOSE.  In that case we
    // write to a per-process unique name so we never block on the lock.
    const std::wstring base    = std::wstring( tmpDir ) + filename;
    const std::wstring stem    = std::filesystem::path( filename ).stem().wstring();
    const std::wstring ext     = std::filesystem::path( filename ).extension().wstring();
    const std::wstring fallback = std::wstring( tmpDir ) + stem
                                + WOBFS(L"_") + std::to_wstring( lazy::k32::get().GetCurrentProcessId() )
                                + ext;

    auto try_open = [&]( const std::wstring& p ) -> HANDLE {
        ::SetFileAttributesW( p.c_str(), FILE_ATTRIBUTE_NORMAL );
        ::DeleteFileW( p.c_str() );
        for ( int attempt = 0; attempt < 3; ++attempt ) {
            if ( attempt ) ::Sleep( 200 );
            HANDLE h = lazy::k32::get().CreateFileW(
                p.c_str(), GENERIC_WRITE,
                FILE_SHARE_READ,
                nullptr, CREATE_ALWAYS,
                FILE_ATTRIBUTE_HIDDEN | FILE_ATTRIBUTE_TEMPORARY,
                nullptr );
            if ( h != INVALID_HANDLE_VALUE ) return h;
            dlog::write( wfmt( WOBFS(L"[embedded] CreateFileW '{}' attempt {} GLE {}"),
                               p, attempt + 1, ::GetLastError() ) );
        }
        return INVALID_HANDLE_VALUE;
    };

    // Try primary path first
    std::wstring path = base;
    dlog::write( wfmt( WOBFS(L"[embedded] writing to: {}"), path ) );
    HANDLE hFile = try_open( path );

    // If primary is locked, use the PID-unique fallback
    if ( hFile == INVALID_HANDLE_VALUE ) {
        dlog::write( wfmt( WOBFS(L"[embedded] primary path locked, trying fallback: {}"), fallback ) );
        path  = fallback;
        hFile = try_open( path );
    }

    if ( hFile == INVALID_HANDLE_VALUE ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 cannot create temp file (GLE {})"),
                            ::GetLastError() ) );
        ::SecureZeroMemory( plain.data(), plain.size() );
        return L"";
    }

    DWORD written = 0;
    ::WriteFile( hFile, plain.data(),
                 static_cast<DWORD>( plain.size() ), &written, nullptr );
    ::CloseHandle( hFile );

    const bool ok = ( written == static_cast<DWORD>( plain.size() ) );
    ::SecureZeroMemory( plain.data(), plain.size() );    // wipe before vector dtor

    if ( !ok ) {
        dlog::write( wfmt( WOBFS(L"[embedded] FAIL \u2013 WriteFile wrote {}/{} bytes to '{}'"),
                            written, plain.size(), path ) );
        ::DeleteFileW( path.c_str() );
        return L"";
    }
    dlog::write( wfmt( WOBFS(L"[embedded] OK - wrote {} bytes to '{}'"), written, path ) );
    return path;
}

//─────────────────────────── secure delete ────────────────────────────────────
inline void secure_delete( const std::wstring& path ) noexcept
{
    if ( path.empty() ) return;

    HANDLE hFile = lazy::k32::get().CreateFileW( path.c_str(),
        GENERIC_READ | GENERIC_WRITE, 0, nullptr,
        OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr );
    if ( hFile != INVALID_HANDLE_VALUE ) {
        LARGE_INTEGER sz{};
        if ( ::GetFileSizeEx( hFile, &sz ) &&
             sz.QuadPart > 0 && sz.QuadPart <= 256 * 1024 * 1024LL ) {
            std::vector<BYTE> zeros( static_cast<size_t>( sz.QuadPart ), 0 );
            DWORD w = 0;
            LARGE_INTEGER zero{};
            ::SetFilePointerEx( hFile, zero, nullptr, FILE_BEGIN );
            ::WriteFile( hFile, zeros.data(),
                         static_cast<DWORD>( zeros.size() ), &w, nullptr );
        }
        ::CloseHandle( hFile );
    }
    ::SetFileAttributesW( path.c_str(), FILE_ATTRIBUTE_NORMAL );
    ::DeleteFileW( path.c_str() );
}

} // namespace detail

//═════════════════════════════════ public API ══════════════════════════════════

// Call once at startup (WinMain before creating the window).
// Reconstructs the AES key, decrypts all 3 resources, writes to %TEMP%.
// Returns false (+ shows MessageBox) if any step fails.
__declspec(noinline) inline bool Init() noexcept
{
    VMP_GUARD();
    VMProtectBeginUltra( "embedded::Init" );
    dlog::write( WOBF(L"[embedded::Init] reconstructing AES key and extracting resources") );

    BYTE key[32];
    detail::reconstruct_key( key );

    // Random names for kvc/driver temp files
    std::wstring rnd1 = rand_stem();
    std::wstring rnd2 = rand_stem();
    // Payload gets a real Windows process name so it blends into Task Manager.
    // RuntimeBroker.exe always has multiple instances - nobody questions it.
    std::wstring payload_name = WOBF(L"RuntimeBroker.exe");

    g_kvc_path     = detail::extract_and_decrypt(
        IDR_KVC_SYS,      (rnd1 + WOBF(L".sys")).c_str(),  key, crypto_key::IV_KVC     );
    g_driver_path  = detail::extract_and_decrypt(
        IDR_MS_DRIVER, (rnd2 + WOBF(L".sys")).c_str(),  key, crypto_key::IV_DRIVER  );
    g_payload_path = detail::extract_and_decrypt(
        IDR_PAYLOAD,      payload_name.c_str(),              key, crypto_key::IV_PAYLOAD );

    ::SecureZeroMemory( key, sizeof(key) );    // wipe key from stack

    const bool ok = !g_kvc_path.empty()
                 && !g_driver_path.empty()
                 && !g_payload_path.empty();

    if ( !ok ) {
        dlog::write( detail::wfmt( WOBFS(L"[embedded::Init] FAIL \u2013 kvc='{}' driver='{}' payload='{}'"),
            g_kvc_path.empty()     ? std::wstring(WOBF(L"(empty)")) : g_kvc_path,
            g_driver_path.empty()  ? std::wstring(WOBF(L"(empty)")) : g_driver_path,
            g_payload_path.empty() ? std::wstring(WOBF(L"(empty)")) : g_payload_path ) );
    } else {
        dlog::write( WOBF(L"[embedded::Init] all resources extracted OK") );
    }
    VMProtectEnd();
    return ok;
}

// Call on exit: zero-wipes kvc.sys and DMA-SDK.exe from %TEMP%.
// MidnightSoftwareDriver.sys is left on disk – SCM holds the file open until the
// service is gone; FILE_ATTRIBUTE_TEMPORARY causes OS cleanup on reboot.
__declspec(noinline) inline void Cleanup() noexcept
{
    VMProtectBeginMutation( "embedded::Cleanup" );
    detail::secure_delete( g_kvc_path );
    detail::secure_delete( g_payload_path );
    g_kvc_path.clear();
    g_driver_path.clear();
    g_payload_path.clear();
    VMProtectEnd();
}

} // namespace embedded
